[ExPort]
net_export = br0
wlan_port  = br0

[MacInfo]
mac_file_path = /tmp/deviceMac.txt
get_mac_sh    = /tmp/netmonitor/script/getMac.sh

[PluginInfo]
Version = 1.3
pluginVersion = 1.5.9

[PlatformInfo]
dpi_address      = wuyou.komect.com
dpi_port      = 15684
config_address   =seap.komect.com
config_port   = 443
ctrl_address     = seap.komect.com
ctrl_port     = 443
register_address = seap.komect.com
register_port = 443


